apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-demo-v1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-demo-v1
    app.kubernetes.io/part-of: sampleapp
  name: quarkus-demo-v1
  namespace: sdoyle
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: quarkus-demo-v1
status:
  loadBalancer: {}
